{% set version = "1.1.2" %}

package:
  name: divebomb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/divebomb/divebomb-{{ version }}.tar.gz
  sha256: 3abaf2acbada366c001b24b9c9ee8cafc8116c00caac0d0761e6deed04ed1eab

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - numpy
    - sphinx
    - plotly
    - netcdf4
    - peakutils
    - scikit-learn
    - ipywidgets
    - xarray
    - colorlover

test:
  imports:
    - divebomb

about:
  home: https://github.com/alexetnunes/divebomb
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'An aquatic animal analysis tool for diving behaviour'
  description: |
    Divebomb is a python package that uses pandas
    to divide a timeseries of depths into individual
    dives and apply machine learning to cluster the
    dives.

  doc_url: http://divebomb.readthedocs.io/
  dev_url: https://github.com/ocean-tracking-network/divebomb

extra:
  recipe-maintainers:
    - alexetnunes
