{% set name = "divebomb" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0d8dd5737c2da30844cce699c288ae051b403adf9368f7a7e0c456a76986dc5

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pandas
    - numpy
    - sphinx
    - plotly
    - netcdf4
    - peakutils
    - scikit-learn
    - ipywidgets
    - xarray
    - colorlover
  run:
    - python
    - pandas
    - numpy
    - sphinx
    - plotly
    - netcdf4
    - peakutils
    - scikit-learn
    - ipywidgets
    - xarray
    - colorlover

test:
  imports:
    - divebomb

about:
  home: https://gitlab.oceantrack.org/anunes/divebomb
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'An marine animal dive analysis tool'
  description: |
    Divebomb is a python package that uses pandas
    to divide a timeseries of depths into individual
    dives and apply machine learning to cluster the
    dives.

  doc_url: http://divebomb.readthedocs.io/
  dev_url: https://gitlab.oceantrack.org/anunes/divebomb

extra:
  recipe-maintainers:
    - alexetnunes
