travis:
  secure:
    BINSTAR_TOKEN: tpPzEfBWvdKeBv4N/IUN708/UHLygMHEcClz/zVrgpgown75SYH3IISWaBD1khj5tSsMJesyz0tNvSFh+ADN/pHlf6hP/AHUw1f7H1FJW+vylBDF21YSmN49f1qYUDGbWmrPY4+fl96ruK92Mp6QL/GucZQyjdYpttGrMjAYC47NrbFC79ZYTeVFc4EH7Jb2eqJUvcUGeAZOJEJmmizE1uWPGYp+LuXdivZ5KpUP/qRufE6Wldobbh2Ksu/d7Qz2lnx4PDYXPwdKH1chi8eTb7WUb0q3bBdtAAqwf4wlk2ouqq0WwL+mhL3bMcuZ2fej9mMuMC93RJhb8tDNkYxixGKtpqiv+trJOvBfEnrEWOc2I6Lt+XzVNzh1d+nJXwdiXP5adCqKB+uaY0L1sdrslrcxAIrJ+HY+EjeBtcfgGf0KAN6oAZXoL1cwNR4Ktgn997W+J/pQy3UEm+YKfvevM9RhjW/uF7HIqCqOiaZk8RL9f+YjUyYLxsZq+ImLMm21pLMN/BdD8EK5MMyF1VJfbopB/X+1jTIHFZNkxsFeMYPO6SJAx4RY9g0umiSYdQ94DUhSCoDMCSYtTXG+lluwpDrBav0IXYL+UAtd8aX55QOFk4IlTQ6ERRyw7i8CnzmMG8HA98miH53j0sZIjDdMIbzlyY+xrtWQ1MZTJv0Xmf0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
